name: linux build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: "ubuntu-22.04"

    permissions:
      contents: read

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v1

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: "18"

      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev libvips-tools libvips

      - name: Install npm deps
        run: |
          npm install

      #- name: Run uncompressed (store) build
      #  run: |
      #    npm run store
      #
      #- name: testrun compiled build
      #  run: |
      #    npm run test
      # this doesn't work because libvips wants to be funny on ubuntu. just run from source.

      - name: Run from source
        run: |
          npm run test -- --from-source